// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yemrlgysuhpoegkjsiuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllbXJsZ3lzdWhwb2Vna2pzaXV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDM3OTYsImV4cCI6MjA2NjcxOTc5Nn0.q4X7hPSUWWhAWqcsbyWmMT2sTp0g1Umd9-FJ9gBFfcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);